package plugins

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// ─── 硬化层验证 ─────────────────────────────────────────

// workflowDef 和 stepDef 用于 YAML 验证的最小结构。
// 只解析验证所需字段，不影响引擎的完整解析。
//
// 注意：这里故意不复用 internal/workflow.WorkflowDef，
// 避免插件层对引擎层产生强依赖（两层保持独立演化）。
type workflowDef struct {
	ID    string    `yaml:"id"`
	Steps []stepDef `yaml:"steps"`
}
type stepDef struct {
	ID      string                 `yaml:"id"`
	Plugin  string                 `yaml:"plugin"`
	Type    string                 `yaml:"type"`
	Timeout int                    `yaml:"timeout,omitempty"`
	OnError string                 `yaml:"on_error,omitempty"`
	Inputs  map[string]interface{} `yaml:"inputs,omitempty"`
}

// validateOnly 对生成的 YAML 做四层校验：
//
//	L1 结构检查  — YAML 可解析，有 id，有步骤
//	L2 插件检查  — 每步引用的 plugin 已注册
//	L3 类型检查  — step.type 在插件支持的 types 列表内
//	L4 V25 规范  — on_error、think_plugin mode、timeout 合理性
//
// V25 规范说明（详见 docs/V25_WORKFLOW_STANDARD.md）：
//   - 每步必须有 on_error（human_confirm 例外，它本身就是终止点）
//   - think_plugin 步骤的 inputs 必须有 mode 字段
//   - 每步 timeout 必须 > 0
func (p *SkillFactoryPlugin) validateOnly(yamlContent string) (string, error) {
	// ── L1 结构检查 ──────────────────────────────────────────
	var def workflowDef
	if err := yaml.Unmarshal([]byte(yamlContent), &def); err != nil {
		return "", fmt.Errorf("YAML 解析失败: %w", err)
	}
	if def.ID == "" {
		return "", fmt.Errorf("工作流缺少 id 字段")
	}
	if len(def.Steps) == 0 {
		return "", fmt.Errorf("工作流没有步骤")
	}

	// ── L2 插件检查 ──────────────────────────────────────────
	known := p.kernel.KnownPlugins()
	pluginSet := make(map[string]bool, len(known))
	for _, name := range known {
		pluginSet[name] = true
	}
	// human_confirm 是引擎内置伪插件，不需要注册
	pluginSet["human_confirm"] = true

	metas := p.kernel.KnownPluginsMeta()

	for _, step := range def.Steps {
		if step.ID == "" {
			return "", fmt.Errorf("存在缺少 id 字段的步骤")
		}
		if step.Plugin == "" {
			return "", fmt.Errorf("步骤 %q 缺少 plugin 字段", step.ID)
		}
		if !pluginSet[step.Plugin] {
			return "", fmt.Errorf("步骤 %q 引用了未注册插件 %q（可用: %s）",
				step.ID, step.Plugin, strings.Join(known, ", "))
		}

		// human_confirm 是伪插件，跳过 type/V25 校验
		if step.Plugin == "human_confirm" {
			continue
		}

		if step.Type == "" {
			return "", fmt.Errorf("步骤 %q 缺少 type 字段", step.ID)
		}

		// ── L3 类型检查 ──────────────────────────────────────
		if m, ok := metas[step.Plugin]; ok && len(m.Types) > 0 {
			valid := false
			for _, t := range m.Types {
				if t == step.Type {
					valid = true
					break
				}
			}
			if !valid {
				return "", fmt.Errorf("步骤 %q 的 type %q 不在插件 %q 支持的类型中: %v",
					step.ID, step.Type, step.Plugin, m.Types)
			}
		}

		// ── L4 V25 规范检查 ───────────────────────────────────
		// 规则1：每步必须声明 on_error，防止一步失败炸掉整条链。
		// 如果确实想让失败终止工作流，应该显式写 on_error: done。
		if step.OnError == "" {
			return "", fmt.Errorf("步骤 %q 缺少 on_error 字段（V25强制项，失败终止请填 on_error: done）", step.ID)
		}

		// 规则2：think_plugin 步骤必须有 mode 字段，防止检索管道干扰 JSON 输出。
		// mode 通常为 "no_retrieval"，引擎也会自动注入，但显式声明更可读。
		if step.Plugin == "think_plugin" {
			if _, hasMode := step.Inputs["mode"]; !hasMode {
				return "", fmt.Errorf("步骤 %q（think_plugin）的 inputs 缺少 mode 字段（推荐 no_retrieval）", step.ID)
			}
		}

		// 规则3：timeout 必须 > 0，防止步骤永久阻塞。
		if step.Timeout <= 0 {
			return "", fmt.Errorf("步骤 %q 的 timeout 必须 > 0（搜索类30，LLM类120-180，通知类15）", step.ID)
		}
	}
	return def.ID, nil
}

func (p *SkillFactoryPlugin) validateAndSave(yamlContent string, force bool) (string, error) {
	name, err := p.validateOnly(yamlContent)
	if err != nil {
		return "", err
	}

	// 4. 检查文件名冲突
	path := filepath.Join(p.workflows, name+".yaml")
	if _, err := os.Stat(path); err == nil {
		if !force {
			return name, ErrSkillExists
		}
		fmt.Printf("[skill_factory] 覆盖已有工作流: %s\n", name)
	}

	// 5. 写入文件
	fullContent := fmt.Sprintf("# Generated by skill_factory_plugin\n# %s\n\n%s",
		time.Now().Format("2006-01-02 15:04:05"),
		yamlContent)
	// D03: skill_factory_plugin 是特权插件，允许直接操作 workflows/ 目录文件系统。
	// 参见 docs/reports/boundary_debt_register.md#D03
	if err := os.MkdirAll(p.workflows, 0755); err != nil {
		return "", fmt.Errorf("创建目录失败: %w", err)
	}
	if err := os.WriteFile(path, []byte(fullContent), 0644); err != nil {
		return "", fmt.Errorf("写入文件失败: %w", err)
	}
	return name, nil
}
